# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - sqlite_data:/app/data
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=your-secret-key-here
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1

volumes:
  sqlite_data: