# Generated by Django 5.1.3 on 2024-11-12 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_address', models.CharField(max_length=42)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=24)),
                ('gas_price', models.DecimalField(decimal_places=18, max_digits=24)),
                ('gas_used', models.DecimalField(decimal_places=18, max_digits=24, null=True)),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nonce', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MultiSigTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_signatures', models.IntegerField(default=2)),
                ('current_signatures', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banking.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('encrypted_private_key', models.TextField()),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.TextField()),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('multi_sig_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.multisigtransaction')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.wallet')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='banking.wallet'),
        ),
        migrations.AddField(
            model_name='multisigtransaction',
            name='signers',
            field=models.ManyToManyField(through='banking.TransactionSignature', to='banking.wallet'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user', 'is_primary'], name='banking_wal_user_id_8277c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionsignature',
            unique_together={('multi_sig_transaction', 'signer')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['from_wallet', 'status'], name='banking_tra_from_wa_c8600d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tx_hash'], name='banking_tra_tx_hash_b17f89_idx'),
        ),
    ]
